### ISSUE TITLE
initialIndex of the bottomNavigationBar?

### ISSUE THREAD

**Issue by miaachan** [therezacuet/Motion-Tab-Bar#1]
Hi dev, the initial tab is still fixed to index 1 in view even the initialIndex of _tabController is set to 0.

```
  @override
  void initState() {
    super.initState();
    _tabController = new MotionTabController(initialIndex: 0,vsync: this);
  }
```

**Comment by therezacuet** [comment]
Thank you for your feedback. I am working on this. It will be fixed on the next release.

**Comment by fabioselau077** [comment]
Same problem.
Good package, thanks for sharing, bro.

**Comment by therezacuet** [comment]
Please try version: 0.1.1

**Comment by therezacuet** [comment]
> Hi dev, the initial tab is still fixed to index 1 in view even the initialIndex of _tabController is set to 0.
> 
> ```
>   @override
>   void initState() {
>     super.initState();
>     _tabController = new MotionTabController(initialIndex: 0,vsync: this);
>   }
> ```

Please try version: 0.1.1

**Comment by MMohsin737** [comment]
Why can't I set an active index myself.
I want to move back to home screen when I press back but there is no option to set active index by myself.
Looking forward for your replay.
