### ISSUE TITLE
Not using safe area on iphone with bottom handel

### ISSUE THREAD

**Issue by nishiths23** [therezacuet/Motion-Tab-Bar#10]
Using the simple example i implemented Motion tab bar on an iphone with bottom handle bar line iphone X and it is observed that there is not much padding between the bottom handle and the tab title.

<img width="364" alt="Screenshot 2020-07-09 at 11 50 46 PM" src="https://user-images.githubusercontent.com/16319917/87076463-716e3e80-c23f-11ea-8e13-676a8a8e5469.png">

And when MotionTabBar is wrapped inside SafeArea or BottomAppBar widget it seems that the whole tab bar breaks

<img width="367" alt="Screenshot 2020-07-09 at 11 55 09 PM" src="https://user-images.githubusercontent.com/16319917/87076631-a2e70a00-c23f-11ea-9eb1-601d60914410.png">

**Comment by therezacuet** [comment]
I am working on this. The issue will fix in the next version. Thanks

**Comment by M3sca** [comment]
Just to join the requested feature. Waiting for an update!
