### ISSUE TITLE
More than 3 iteams in bottom bar

### ISSUE THREAD

**Issue by petarkovac** [therezacuet/Motion-Tab-Bar#12]
This parameter should be optional, or at least to expect no more than 5 elements as UI/UX suggest for every application.

https://github.com/therezacuet/Motion-Tab-Bar/blob/bbb2b514b92061984b23322c733d2547d0e574c0/lib/MotionTabController.dart#L7

**Comment by zyllus17** [comment]
Change length to 4 or 5 if you want that many buttons at the bottom.

**Comment by petarkovac** [comment]
Thanks for the feedback.
I'll close this issue, it was my mistake for not seeing that part.
