### ISSUE TITLE
How to deactivate bulge animation

### ISSUE THREAD

**Issue by zyllus17** [therezacuet/Motion-Tab-Bar#13]
I have four buttons in Bottom Nav bar, I want it to be deactivated and be plain when it is not in those specific pages. Any way I can do it now?

**Comment by zyllus17** [comment]
@therezacuet Any way I can do this?

**Comment by therezacuet** [comment]
I am working on this.

**Comment by zyllus17** [comment]
@therezacuet Can you give me a timeframe, if its gonna be late then I have to custom build it myself

**Comment by ikhaled-elazab** [comment]
I'm working with this aswell, would love to see something like this with 5 buttons

**Comment by ikhaled-elazab** [comment]
> @therezacuet Can you give me a timeframe, if its gonna be late then I have to custom build it myself

@zyllus17 If you do create something custom for this would you please share any progress? Thank you!

**Comment by zyllus17** [comment]
> > @therezacuet Can you give me a timeframe, if its gonna be late then I have to custom build it myself
> 
> @zyllus17 If you do create something custom for this would you please share any progress? Thank you!

@shw2ypro I did some research on this and found that you cannot deactivate all at once, one has to remain active at all times, its just how Flutter works. There is a work around though, if you use a default navbar you can make it force the UI to show it null even though it will be active/elevated. I don't have time to build it as of now but if I get time, I will notify you.

**Comment by zyllus17** [comment]
> > > @therezacuet Can you give me a timeframe, if its gonna be late then I have to custom build it myself
> > 
> > 
> > @zyllus17 If you do create something custom for this would you please share any progress? Thank you!
> 
> @shw2ypro I did some research on this and found that you cannot deactivate all at once, one has to remain active at all times, its just how Flutter works. There is a work around though, if you use a default navbar you can make it force the UI to show it null even though it will be active/elevated. I don't have time to build it as of now but if I get time, I will notify you.

@shw2ypro I found something which may help you. Check this article, from it you can build the same bottom navigation bar on your own.
https://medium.com/@tonyowen/flutter-bottom-tab-bar-animation-75d1ca58c096
