### ISSUE TITLE
Page transition activate initState of in-between pages

### ISSUE THREAD

**Issue by crkumar425** [therezacuet/Motion-Tab-Bar#16]
The current tab is 1, if i want to move to 5th tab, if tab3 and tab4 have initState function, during the transition from tab1 to tab5, it activate the initState function of tab3 and tab4. This cause some issue. Is there any way to disable it. 
Thank you.

**Comment by therezacuet** [comment]
@crkumar425 Please see the new version released. I believe your issue is incorporated on the latest. ([v2.0.3](https://pub.dev/packages/motion_tab_bar))
