### ISSUE TITLE
issues in animation

### ISSUE THREAD

**Issue by mohammadmiiad** [therezacuet/Motion-Tab-Bar#18]
i have problem in animation 
recive a error 
![Capture](https://user-images.githubusercontent.com/71085293/98089085-85494a80-1e97-11eb-8274-b73141aee5b1.PNG)
But shifts are made between pages

**Comment by therezacuet** [comment]
@mohammadmiiad New version is now available on ([v2.0.3](https://pub.dev/packages/motion_tab_bar)) with fixed pesky bugs, RTL support and supports Flutter 3 also.
