### ISSUE TITLE
Switch TAB via Function

### ISSUE THREAD

**Issue by cmregazzo** [therezacuet/Motion-Tab-Bar#19]
Hi,

Is it possible to change TAB via function?

For example, I click a button, and change the TAB as if I clicked it.

Thanks.

**Comment by therezacuet** [comment]
@cmregazzo Switch TAB via function, RTL support is now available on the new release ([v2.0.3](https://pub.dev/packages/motion_tab_bar)) with fixed pesky bugs, and supports Flutter 3.
