### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by BechirAhmed** [therezacuet/Motion-Tab-Bar#22]

**Comment by mohammeddawida** [comment]
Is the package support RTL ?

**Comment by MRezaSafari** [comment]
> Is the package support RTL ?

nah

**Comment by therezacuet** [comment]
@MRezaSafari @mohammeddawida @BechirAhmed RTL support is now available on the new release ([v2.0.3](https://pub.dev/packages/motion_tab_bar)) with fixed pesky bugs, and supports Flutter 3 also.
