### ISSUE TITLE
Padding needed on iOS, overlapping occurs

### ISSUE THREAD

**Issue by rgbinnovation** [therezacuet/Motion-Tab-Bar#24]
Hi,

Padding is needed on iOS. As you can see on the attached image, the lower iOS "Action Bar" overlaps the navigation texts. Maybe some additional padding could be added?
![IMG_5283](https://user-images.githubusercontent.com/3257827/116677731-221a1a00-a9db-11eb-8163-ec1ee4505c19.jpg)

**Comment by rgbinnovation** [comment]
Thanks to your replies to my other comments. Is this something you could look into as well? Love the package but this looks terrible on iOS.

**Comment by MRezaSafari** [comment]
> Thanks to your replies to my other comments. Is this something you could look into as well? Love the package but this looks terrible on iOS.

have you tried wrap it in SafeArea widget ?

**Comment by rgbinnovation** [comment]
Thanks, will try it, appreciate the suggestions Were you able to to add the ability to change colors, by any chance?

**Comment by MRezaSafari** [comment]
> Thanks, will try it, appreciate the suggestions Were you able to to add the ability to change colors, by any chance? Sent from my iPhone. Please excuse brief replies.
> […](#)
> On Jun 20, 2021, at 18:13, Mohammad Reza Safari ***@***.***> wrote: ﻿ Thanks to your replies to my other comments. Is this something you could look into as well? Love the package but this looks terrible on iOS. have you tried wrap it in SafeArea widget ? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

no, I simply droped this library in my project. no RTL support . no resizing for icons. it's so simple. if I just find enough time I will make a fork out of it and fix these issues.

**Comment by therezacuet** [comment]
Hi @rgbinnovation @MRezaSafari Sorry for the late reply, due to some unavoidable circumstances I was not able to maintain this package for long days. Now I am back and have fixed all issues and released a new version([v2.0.3](https://pub.dev/packages/motion_tab_bar)). I believe most of the issues are fixed now with RTL support, icon resizing, bg color changes, etc.
