### ISSUE TITLE
Abandoned package?

### ISSUE THREAD

**Issue by rgbinnovation** [therezacuet/Motion-Tab-Bar#25]
Has this package been abandoned? There is zero replies from the developer.

**Comment by therezacuet** [comment]
Sorry for late reply man. Actually i was in trouble due to covid and i didn't do any work. I will start to maintain this package soon. Thanks for your feedback.

**Comment by rgbinnovation** [comment]
Sorry to hear that, but good to hear that you are OK now. Looking forward to be able to switch back to using it.

Respectfully,

Robert
