### ISSUE TITLE
Cannot implement dark theme on application. How to change background color??

### ISSUE THREAD

**Issue by Subash22** [therezacuet/Motion-Tab-Bar#26]
how can I change the background color of the motion tab bar it's default color id white background and can't change it.

**Comment by kimmanwky** [comment]
Seems like author MIA. I have published a new v2 package. 

Please refer to [https://pub.dev/packages/motion_tab_bar_v2](https://pub.dev/packages/motion_tab_bar_v2).

**Comment by erperejildo** [comment]
> Seems like author MIA. I have published a new v2 package.
> 
> Please refer to https://pub.dev/packages/motion_tab_bar_v2.

that "new" package was updated 10 months ago while this one got more recent updates. What's the difference?

**Comment by therezacuet** [comment]
@erperejildo This one is the most updated.
