### ISSUE TITLE
Please update to null safety version

### ISSUE THREAD

**Issue by AltRoot17** [therezacuet/Motion-Tab-Bar#27]
Please update to null safety version

**Comment by kimmanwky** [comment]
Seems like author MIA. I have published a new v2 package. 

Please refer to [https://pub.dev/packages/motion_tab_bar_v2](https://pub.dev/packages/motion_tab_bar_v2).

**Comment by therezacuet** [comment]
@AltRoot17 RTL support is now available on the new release ([v2.0.3](https://pub.dev/packages/motion_tab_bar)) with fixed pesky bugs, and supports Flutter 3 also.
