### ISSUE TITLE
Update null safety version.

### ISSUE THREAD

**Issue by aminsamad** [therezacuet/Motion-Tab-Bar#28]

**Comment by kimmanwky** [comment]
Seems like author MIA. I have published a new v2 package. 

Please refer to [https://pub.dev/packages/motion_tab_bar_v2](https://pub.dev/packages/motion_tab_bar_v2).

**Comment by therezacuet** [comment]
@aminsamad RTL support is now available on the new release ([v2.0.3](https://pub.dev/packages/motion_tab_bar)) with fixed pesky bugs, and supports Flutter 3 also.
