### ISSUE TITLE
[PLEASE READ] Due to contributor inactivity, this package has been forked as "motion_tab_bar_v2" with null-safety support

### ISSUE THREAD

**Issue by kimmanwky** [therezacuet/Motion-Tab-Bar#30]
The fork is available at [motion_tab_bar_v2](https://github.com/kimmanwky/Motion-Tab-Bar), with null-safety support.

Package is available here: [https://pub.dev/packages/motion_tab_bar_v2](https://pub.dev/packages/motion_tab_bar_v2)

Issues and Pull Requests are welcome.

**Comment by memmen** [comment]
Thank you!
