### ISSUE TITLE
icons motion is not correct with RTL direction

### ISSUE THREAD

**Issue by BlueSoftec** [therezacuet/Motion-Tab-Bar#32]
icons motion is not correct with RTL direction

![Screenshot_1651682582](https://user-images.githubusercontent.com/10473829/166731549-6185b9c8-8594-42d3-a12a-7c401e6d7c21.png)

**Comment by 14mohamedahmed** [comment]
Hey @BlueSoftec Did you find the solution?

**Comment by therezacuet** [comment]
Hi @BlueSoftec @14mohamedahmed RTL support is now available on the new release ([v2.0.3](https://pub.dev/packages/motion_tab_bar)), fixed pesky bugs, and supports flutter 3 also.
