### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by yanashenyang** [therezacuet/Motion-Tab-Bar#34]
======== Exception caught by widgets library =======================================================
The following LateError was thrown building MotionTabBar(dirty, dependencies: [Directionality], state: _MotionTabBarState#0dda9):
LateInitializationError: Field 'labels' has not been initialized.

**Comment by yanashenyang** [comment]
======== Exception caught by widgets library ============
The following LateError was thrown building MotionTabBar(dirty, dependencies: [Directionality], state: _MotionTabBarState#0dda9):
LateInitializationError: Field 'labels' has not been initialized.

**Comment by therezacuet** [comment]
@yanashenyang **motion_tab_bar: ^2.0.4** released with the fix.
