### ISSUE TITLE
example bug

### ISSUE THREAD

**Issue by yanashenyang** [therezacuet/Motion-Tab-Bar#35]
example bug
example project cannot run
example project cannot run
example project cannot run
example project cannot run
example project cannot run

**Comment by therezacuet** [comment]
@yanashenyang You have to create a new project and then add the **motion_tab_bar** dependency. example folder only shows the single file with the implementations. If you try to close this project and run directly will not work anymore. Please check the readme of this package. Thanks for the using **motion_tab_bar**.
