### ISSUE TITLE
bug in Flutter 3.16.3

### ISSUE THREAD

**Issue by yanashenyang** [therezacuet/Motion-Tab-Bar#36]
Flutter 3.16.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0366e0a3f (4 weeks ago) • 2023-12-05 19:46:39 -0800
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4

demo project can not run

**Comment by therezacuet** [comment]
@yanashenyang motion_tab_bar: ^2.0.4 released with the fix. Thanks
