### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by AlexBolot** [therezacuet/Motion-Tab-Bar#4]
Hi Rezaul !
I've been using this repository for a flutter project, and I had to make changes to the MotionTabBar class you provide. I think it could be interesting that I share with you my modifications through a Pull Request, if you're interested in accepting contribution to you repository 😃 

If it's OK for you, let me know 😃 

Alexandre

**Comment by therezacuet** [comment]
Yes Sure. This repository always opens for contribution.

**Comment by AlexBolot** [comment]
There it is : #5 
Don't hesitate to ask me any question about this Pull Request if needed 😃

**Comment by evertonAlvaro** [comment]
Great changes Alex. Very interesting the feature of having more tabs.
But when I place more than 3 tabs, I get the following error:
'package: motion_tab_bar / MotionTabController.dart': Failed assertion: line 50 pos 12: 'value> = 0 && (value <length || length == 0)': is not true.

pubspec.yaml:
motion_tab_bar: 
    git:
      url: https://github.com/AlexBolot/Motion-Tab-Bar.git
      ref: master

**Comment by AlexBolot** [comment]
Hi @evertonAlvaro, can you send me the code where you trying adding more than 3 tabs ?

**Comment by mnomanmemon** [comment]
@therezacuet When this feature is available?

**Comment by AlexBolot** [comment]
@mnomanmemon The feature has been merged on master, so the only missing step is a new version published on [pub.dev]( pub.dev) 😃  So I guess it'll be available quite soon 😉

**Comment by mnomanmemon** [comment]
eagerly waiting for this man

**Comment by AlexBolot** [comment]
That's nice to hear ! In the mean time you can always include the source files in your project : either from [here](https://github.com/therezacuet/Motion-Tab-Bar/tree/master) or [there](https://github.com/AlexBolot/Motion-Tab-Bar/tree/master). And when the new version is published you'll delete the files and replace with the dependency :)

**Comment by therezacuet** [comment]
New release will be published soon. Thanks

**Comment by therezacuet** [comment]
Version 0.1.4 released.

**Comment by mnomanmemon** [comment]
@therezacuet @AlexBolot issue is still exist:

The following assertion was thrown while handling a gesture:
'package:motion_tab_bar/MotionTabController.dart': Failed assertion: line 50 pos 12: 'value >= 0 && (value < length || length == 0)': is not true.
