### ISSUE TITLE
Big ISSUE!!!!!!!

### ISSUE THREAD

**Issue by MianSaadHafeez646** [therezacuet/Motion-Tab-Bar#8]
We can't change the background color of the tab bar

**Comment by therezacuet** [comment]
I am working on this. I hope you will get it in next version soon. Thanks for your feedback.

**Comment by patzobil** [comment]
Hello @therezacuet ,

Any chance you have managed the background color change?
Thanks a lot

**Comment by kimmanwky** [comment]
Seems like author MIA. I have published a new v2 package. 

Please refer to [https://pub.dev/packages/motion_tab_bar_v2](https://pub.dev/packages/motion_tab_bar_v2).
